### PR TITLE
Fixed last-outcome triangle display for categorical markets, including in "my positions"

### PR DESCRIPTION
**Pull request by unparalleled-js**
https://app.clubhouse.io/augur/story/17082/triangle-market-indicators-off-for-multi-value-markets

### CODE REVIEW

**Comment by adrake33** [comment]
@unparalleled-js Can you modify this so that the arrows are aligned vertically? I think they used to look like that on the Markets page (though I'm not sure about the Trading page).

**Comment by unparalleled-js** [comment]
> @unparalleled-js Can you modify this so that the arrows are centered vertically? I think they used to look like that on the Markets page (though I'm not sure about the Trading page).

Done! I put updated pics on Clubhouse

**Comment by unparalleled-js** [comment]
@adrake33 I just added a solution that makes dealing with the conflicting spacings easier ... and updated photos on clubhouse

**Comment by unparalleled-js** [comment]
@adrake33 Made changes!

**Comment by unparalleled-js** [comment]
@adrake33  https://app.clubhouse.io/augur/story/17160/arrow-indicator-in-positions-placement-is-off
fixed those positions arrows in this PR

**Comment by unparalleled-js** [comment]
I zoomed in on all of the arrows to make them as centered as I could.

**Pull request merged**
