### PR TITLE
Removes Website wording in resolution source during market creation.

### PR DESCRIPTION
**Pull request by MicahZoltu**

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Pretty sure this will break any tests, but wanted to get the proposal out there and started.  Someone who actually knows what they are doing, feel free to take this over.  :)

**Comment by MicahZoltu** [comment]
Why didn't this fail?  https://github.com/AugurProject/augur-ui/blob/master/integration/create-market.test.ts#L158  Are tests not run as part of CI?

**Comment by bthaile** [comment]
I think there is a market creation test that needs to be updated. And look, there might be another instance of that phrase in the market creation code.

**Comment by nuevoalex** [comment]
I don't think we have any tests that just check if all copy is what we set it to. In general any test I'd want a script to update for me isn't very useful

**Comment by pgebheim** [comment]
Those tests (the integration ones) don't run in CI because they're so flakey.

**Pull request merged**
