### PR TITLE
johndanz/ch17176/associate-localstorage-variable-selecteduniverse

### PR DESCRIPTION
**Pull request by JohnDanz**
re-keyed localStorage selectedUniverse to be keyed by account and network id now.

### CODE REVIEW

**Comment by adrake33** [comment]
@JohnDanz I used Flash to create a fork and then went to the Account:Universes page and selected a child universe. After doing so, my account's local storage changed from :

```
favorites: {}
gasPriceInfo: {}
notifications: []
pendingLiquidityOrders: {}
reports: {}
scalarMarketsShareDenomination: {}
selectedUniverse: {102: "0xaac01b4aaa2ebd04a4790c85b76e1749d8ef8e13"}
```
to 
```
[object Object]
```
The Accounts:Universe page also showed an error dialog saying "Sorry, something went wrong! Try reloading this page or returning home." 

Prior to attempting to select a child universe, though, `selectedUniverse` seemed to be getting set correctly.

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 52c5f196712d9a5fae76c7fe97981e80a5eb3908 into b035ad7b82955801fc66b8fd7b3fa6d0b0add21f - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-dac6caa8fb203593e8f92b42c2e48f9e47ecbff3)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 380480eda40b4ab09f3e5f418dc3e9b688fb7c1c into ba57d03a0d1cb502229e04b82f6754dcd6c3060e - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-ca76a3bfd105d37cc46df27283cf950b5e7f1705)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 568cded96750a1ced11b5f5a1aa0979c75f820a0 into 9a3a27a8a08e6dc390bf59938cda9e0dd2f6ce68 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-e736e4488c01c3cd244a12fcf4034f2509f3883a)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 0838a0e3a7f115e2ff707c9d7bb052128e463ed7 into 9a3a27a8a08e6dc390bf59938cda9e0dd2f6ce68 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-0d01b203778af7b98a44debadb50811463d00288)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 2b233c5fbdc1b84c0eecbd64cb18627fea556725 into c184015c88f43dbae4a5d79436b0951290d17bd1 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-4d69aa222079923b7e562e641390639eb5858d74)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 2646039cd714802872d48276ed05807a947912c2 into 7c6f7c917cf648c5e21edc8fd5d224873d724e26 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-4d3a3956b845b9ae9d67bb793d443ae4d745f4b3)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 1844daff0b30a276826c825afa511669da014778 into d1a71a37ded8c6688895ccec44856342efa81669 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-2bea86bb537e659f6e7eaff969d9a06eb043b85c)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging ca7346cd903d0b9e347115e218c490daf778f36d into d1a71a37ded8c6688895ccec44856342efa81669 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-fd3e6a68f5d6e6a903d8e39492074bf85d63c929)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 4d68af4c463f4f1bd69e8054eaf6b1b64f1011f6 into c551ad0a7a87d05fc998a23bfe4daeb38a8f6106 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-06d57d729d2adc311ae01223c0e41af677392e4c)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 10c838bb35660e8bc6da70e32f4f38740ba72761 into c551ad0a7a87d05fc998a23bfe4daeb38a8f6106 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-5803ee199d94912c074eea152b4020e5104085f9)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging d4a6cb1cecd58fdd4152c2a0ff1c552c3e8b425c into c8af343294db0242ae95af2eb8a381786458bd7c - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-07d051d95360ea0d5d4eadf05f9ba619d677189f)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by JohnDanz** [comment]
travis is failing, but if you look it's failing on the linting that i fixed in the last commit, which it's not testing. It's testing commit 10c838b but not d4a6cb1 which fixes the prop issue.

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging bc38e40bbb541902ea970ff355ea11ee42effa19 into 914075694d3691387c7935f9207975500d662aba - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-ff4967c14f21c895b3b88f442b0b6dddc90449db)

**fixed alerts:**

* 1 for Clear text storage of sensitive information

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
