### PR TITLE
Fixed issue allowing user to edit network connection

### PR DESCRIPTION
**Pull request by unparalleled-js**
https://app.clubhouse.io/augur/story/15774/use-current-transport-name-to-determine-if-using-metamask

### CODE REVIEW

**Comment by bthaile** [comment]
Is there a Clubhouse task for this?

**Comment by tinybike** [comment]
@bthaile Yes, the CH task is shown in the branch name, [ch15774](https://app.clubhouse.io/augur/story/15774/use-current-transport-name-to-determine-if-using-metamask).  @justinbarry @bthaile @unparalleled-js this PR has been open for quite a while, what's needed to merge this?

**Comment by bthaile** [comment]
Getting this error, have confirmed I have ethrpc version 5.5.5, seems something got missed.

screen shot 2018-09-13 at 1 18 56 pm

**Comment by justinbarry** [comment]
Did you pull in the new commits?

**Comment by phoebemirman** [comment]
yep

**Comment by justinbarry** [comment]
Looks good!

image

**Pull request merged**
