### PR TITLE
Enabled helmet

### PR DESCRIPTION
**Pull request by joeykrug**

### CODE REVIEW

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 74d2b8a727f463766b1137b6953b81f5db384fcc into 03b06ca3f07ef7ca2698021d854e583b27a42e1c - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-7f32a5880c402664b0ca38309da29f2125a19641)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by joeykrug** [comment]
(Yeah I bet people will use it for other stuff so figured cant hurt to wear a helmet haha)

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 6b52a74e7196b259f75905b5e697109296160620 into 7dac0ccc0d5d7a24fef6fcf092b5e5a1bf729902 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-3566e4b10d0527a4da2899a180b5fa35660d0fb1)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **fixes 1 alert** when merging 0b2b27d7d6aa5c10b92532923a46f3d836ceb9dc into f2c000959a15e65e48d4c9e174272ceaae9ceadb - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-218b3fd54e72018920c4b13e64a615db532dd9e4)

**fixed alerts:**

* 1 for Unused variable, import, function or class

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
