### PR TITLE
Dropdown active selection issues

### PR DESCRIPTION
**Pull request by andrewdamelio**
Three bugs/issues have been addressed in this PR related to drop down boxes.

1) Hover color does not stay on dropdown selector when the cursor moves off of it. 
https://github.com/AugurProject/augur/issues/1091

**BUG** -> http://recordit.co/wGZEOJAYDv
**FIX** -> http://recordit.co/wns4h1OPMm

2) dropdown items height is determined by the standard height of the dropdown button
https://github.com/AugurProject/augur/issues/1395

**FIX**
Screen Shot 2019-03-20 at 4 15 31 PM
Screen Shot 2019-03-20 at 4 15 20 PM

3) dropdown width is determined by the widest item in the list.
https://github.com/AugurProject/augur/issues/1395

**BUG**
image

**FIX**
Screen Shot 2019-03-20 at 4 28 31 PM

### CODE REVIEW

**Comment by bthaile** [comment]
image

need to remove the select outline

**Comment by bthaile** [comment]
still seeing, not sure if you have tried to address it.

image

**Comment by andrewdamelio** [comment]
@bthaile fixed on my end but haven't pushed up yet. Trying to clean up the solution a bit.

**Comment by bthaile** [comment]
can you fix conflicts,
also are the px values going to work well on different resolutions? Isn't that why we use `rem`

**Comment by andrewdamelio** [comment]
@bthaile alright its all updated now. 

Please let me know if you notice any other drop downs having issues, I believe I got them all though.
I also removed the blue focus outline.

**Pull request merged**
