### PR TITLE
Merge tests back

### PR DESCRIPTION
**Pull request by bthaile**
fixes https://github.com/AugurProject/augur/issues/619

remove __mocks__ folders (manual mocks are our bag) removed tests that I couldn't get to pass, since removing the mocks `createSelector` tests.

had to rearrange imports b/c babel would throw a fit. weird. So no
```
import { augur } ....
```
It likes 
```
import makePath from ... 
```
so no deconstructed imports on first line.

make sure to smash this PR

node 9 and node 10 work, tests also passed using v8.14.0. CI isn't happy. It's using yarn `v1.3.2`, might need to upgrade to version 1.10.0 or 1.12.3

### CODE REVIEW

**Comment by AugurIntegration** [comment]
This pull request **introduces 5 alerts** and **fixes 1** when merging 5049facdfb548479307cc155a2691f393c7a28a4 into a1e2111fc8db4d20721a7e9908bfe5e59da37da3 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-54318d60f9763ae730fcfb8c7da223ec18fefe13)

**new alerts:**

* 5 for Superfluous trailing arguments

**fixed alerts:**

* 1 for Useless assignment to property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **introduces 5 alerts** and **fixes 1** when merging 147cada3aefe05ad64028093a6424f8ff1039171 into 0c2b681143145f04592953480bcc8f40ae87c2bb - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-6fff35a9a608be34e21bcca0b7ee32e8b12934d0)

**new alerts:**

* 5 for Superfluous trailing arguments

**fixed alerts:**

* 1 for Useless assignment to property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by justinbarry** [comment]
Failing in CI. Trying to figure out why.

**Comment by AugurIntegration** [comment]
This pull request **introduces 5 alerts** and **fixes 1** when merging 3013828ae32ac39faa3348ff97898d6021f65e0b into 0fe4ce95b5a213364846f97a5449fd3ee266c294 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-6c35a29e72eb393622ce6f181e49d4dda3ce4e9f)

**new alerts:**

* 5 for Superfluous trailing arguments

**fixed alerts:**

* 1 for Useless assignment to property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **introduces 5 alerts** and **fixes 1** when merging 48fb4e5c9327e5fcce155e62fcf94c3fc856f018 into 0fe4ce95b5a213364846f97a5449fd3ee266c294 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-02a51ad623340754775d60b9287e25aa5badc9ba)

**new alerts:**

* 5 for Superfluous trailing arguments

**fixed alerts:**

* 1 for Useless assignment to property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **introduces 5 alerts** and **fixes 1** when merging 65180ad538ee6ecd6edfecf485223619f885d68a into 0fe4ce95b5a213364846f97a5449fd3ee266c294 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-e119e6bd757ce89db49277241b2d29da5cdd9213)

**new alerts:**

* 5 for Superfluous trailing arguments

**fixed alerts:**

* 1 for Useless assignment to property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **introduces 5 alerts** and **fixes 1** when merging 44e59a70463692d54b08238c4aeff792bdd344a5 into 0fe4ce95b5a213364846f97a5449fd3ee266c294 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-f3354ea1e80b0203d09f1b4e5050636acf8b3bbe)

**new alerts:**

* 5 for Superfluous trailing arguments

**fixed alerts:**

* 1 for Useless assignment to property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AugurIntegration** [comment]
This pull request **introduces 5 alerts** and **fixes 1** when merging d2c2300a56f6cdd38d0ad3d10bdaa10abaf55e5f into 0fe4ce95b5a213364846f97a5449fd3ee266c294 - [view on LGTM.com](https://lgtm.com/projects/g/AugurProject/augur-ui/rev/pr-25b058f8bb8b40d7c87a108251fc8a9500ff0fe5)

**new alerts:**

* 5 for Superfluous trailing arguments

**fixed alerts:**

* 1 for Useless assignment to property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
